input_branches: # will be loaded from input ROOT files
  - muPt
  - tauPt
  - ditauPt
  - Njets
  - leadingjetPt
  - subleadingjetPt
  - dijetPt
  - dijetMass
  - dijetdeltaEta
  - pairvisMass
  - fastMTTmass
  - PUPPImet
  - muMETmt
  - evt
  - run
  - wEven
  - wOdd
  - wMM
  - wPrefiring
  - wIDvsJet
  - wIDvsEle
  - wIDvsMu
  - wTrg
  - wIDMu
  - wTrkMu
  - wPU
  - wZpT
  - wToppT
  - wBtag
  - wMC
  - wSignal
  
cont_features: # will be stored in the output foldfile as continuous features
  - muPt
  - tauPt
  - ditauPt
  - Njets
  - leadingjetPt
  - subleadingjetPt
  - dijetPt
  - dijetMass
  - dijetdeltaEta
  - pairvisMass
  - fastMTTmass
  - muMETmt
  - PUPPImet
cat_features: # will be stored in the output foldfile as categorical features
misc_features: # will be stored in the output foldfile as miscellaneous features
  - evt
  - run
  - w_class_imbalance # see definition in preprocess.py