defaults:
  - ../preprocess/prediction_data@_global_.preprocess_cfg: cp_htt_mutauh
  - _self_

kind: 'for_datacards'

# mflow cfg
experiment_id: ???
run_id: ???

# input path & info
year: ???
orig_path: ${preprocess_cfg.input_path}
orig_filename_template: ${preprocess_cfg.input_filename_template}
input_path: ${preprocess_cfg.output_path}
input_filename_template: ${preprocess_cfg.output_filename_template}.h5
sample_names: ${preprocess_cfg.input_samples}
input_tree_name: HTauTauTree/Nominal


# output section
misc_features: # will be added to output ROOT file along with prediction branches
    - evt
    - run
    - wPrefiring
    - wIDvsJet
    - wIDvsEle
    - wIDvsMu
    - wTrg
    - wIDMu
    - wTrkMu
    - wPU
    - wZpT
    - wToppT
    - wMC
    - wSignal
#   - wBtag
#   - w_class_imbalance # see definition in preprocess.py
output_filename_template: '{sample_name}_pred.root'
output_tree_name: HTauTauTree
