for_training: False
compute_w_CP: False
defaults:
  - ../features@_global_: cp_htt_mutauh
  - _self_

# override values
misc_features: # will be stored in the output foldfile as miscellaneous features
  - evt
  - run
  - weight

# input section
year: ???
input_path: /home/sfalke/pbsSpace/HtautauCP/Run2/NTuples/11_2022_ProdMario/UL2018
input_filename_template: '{sample_name}.root' # assume the same pattern for all input sample files
input_tree_name: HTauTauTree/Nominal
input_samples:

  - H_tautau_ggF
  - EWKWMinus2Jets_Wlnu
  - EWKWPlus2Jets_Wlnu
  - EWKZ2Jets_Zll
  - ST_tW_antitop
  - ST_tW_top
  - WminusHToTauTau
  - WW_2l2nu
  - WZ_1l3nu
  - WZ_3l1nu
  - ZZ_2l2nu
  - ZZ_2l2q
  - ZZ_4l

input_pipe_file: 'data/mutau/UL2018/skims/os/input_pipe.pkl' # relative path

# output section
output_path:  'data/mutau/UL2018/skims/os/for_prediction' # relative path
output_filename_template: '{sample_name}' # {sample_name} here will be filled with names from "input_samples" above

# total weight
weights:
  - wPrefiring
  - wIDvsJet
  - wIDvsEle
  - wIDvsMu
  - wTrg
  - wIDMu
  - wTrkMu
  - wPU
  - wZpT
  - wToppT
  - wMC
  - wSignal
#  - wBtag
