# features to be used for training in the mu tauh channel
cont_features:
  - muPt
  - tauPt
  - ditauPt
  - Njets
  - leadingjetPt
  - subleadingjetPt
  - dijetPt
  - dijetMass
  - dijetdeltaEta
  - pairvisMass
  - fastMTTmass
  - muMETmt
  - PUPPImet
cat_features:

# training weight
#weight_name: 'wPrefiring*wIDvsJet*wIDvsEle*wIDvsMu*wTrg*wIDMu*wTrkMu*wPU*wZpT*wToppT*wBtag*wMC*wSignal'
weight_name: weight
